// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/ground_truth/proto/relations.proto

#ifndef PROTOBUF_cartographer_2fground_5ftruth_2fproto_2frelations_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fground_5ftruth_2fproto_2frelations_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "cartographer/transform/proto/transform.pb.h"
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace ground_truth {
namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_cartographer_2fground_5ftruth_2fproto_2frelations_2eproto();
void protobuf_AssignDesc_cartographer_2fground_5ftruth_2fproto_2frelations_2eproto();
void protobuf_ShutdownFile_cartographer_2fground_5ftruth_2fproto_2frelations_2eproto();

class GroundTruth;
class Relation;

// ===================================================================

class Relation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.ground_truth.proto.Relation) */ {
 public:
  Relation();
  virtual ~Relation();

  Relation(const Relation& from);

  inline Relation& operator=(const Relation& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Relation& default_instance();

  void Swap(Relation* other);

  // implements Message ----------------------------------------------

  inline Relation* New() const { return New(NULL); }

  Relation* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Relation& from);
  void MergeFrom(const Relation& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Relation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 timestamp1 = 1;
  void clear_timestamp1();
  static const int kTimestamp1FieldNumber = 1;
  ::google::protobuf::int64 timestamp1() const;
  void set_timestamp1(::google::protobuf::int64 value);

  // optional int64 timestamp2 = 2;
  void clear_timestamp2();
  static const int kTimestamp2FieldNumber = 2;
  ::google::protobuf::int64 timestamp2() const;
  void set_timestamp2(::google::protobuf::int64 value);

  // optional .cartographer.transform.proto.Rigid3d expected = 3;
  bool has_expected() const;
  void clear_expected();
  static const int kExpectedFieldNumber = 3;
  const ::cartographer::transform::proto::Rigid3d& expected() const;
  ::cartographer::transform::proto::Rigid3d* mutable_expected();
  ::cartographer::transform::proto::Rigid3d* release_expected();
  void set_allocated_expected(::cartographer::transform::proto::Rigid3d* expected);

  // optional double covered_distance = 4;
  void clear_covered_distance();
  static const int kCoveredDistanceFieldNumber = 4;
  double covered_distance() const;
  void set_covered_distance(double value);

  // @@protoc_insertion_point(class_scope:cartographer.ground_truth.proto.Relation)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 timestamp1_;
  ::google::protobuf::int64 timestamp2_;
  ::cartographer::transform::proto::Rigid3d* expected_;
  double covered_distance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fground_5ftruth_2fproto_2frelations_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fground_5ftruth_2fproto_2frelations_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fground_5ftruth_2fproto_2frelations_2eproto();

  void InitAsDefaultInstance();
  static Relation* default_instance_;
};
// -------------------------------------------------------------------

class GroundTruth : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.ground_truth.proto.GroundTruth) */ {
 public:
  GroundTruth();
  virtual ~GroundTruth();

  GroundTruth(const GroundTruth& from);

  inline GroundTruth& operator=(const GroundTruth& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GroundTruth& default_instance();

  void Swap(GroundTruth* other);

  // implements Message ----------------------------------------------

  inline GroundTruth* New() const { return New(NULL); }

  GroundTruth* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GroundTruth& from);
  void MergeFrom(const GroundTruth& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GroundTruth* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .cartographer.ground_truth.proto.Relation relation = 1;
  int relation_size() const;
  void clear_relation();
  static const int kRelationFieldNumber = 1;
  const ::cartographer::ground_truth::proto::Relation& relation(int index) const;
  ::cartographer::ground_truth::proto::Relation* mutable_relation(int index);
  ::cartographer::ground_truth::proto::Relation* add_relation();
  ::google::protobuf::RepeatedPtrField< ::cartographer::ground_truth::proto::Relation >*
      mutable_relation();
  const ::google::protobuf::RepeatedPtrField< ::cartographer::ground_truth::proto::Relation >&
      relation() const;

  // @@protoc_insertion_point(class_scope:cartographer.ground_truth.proto.GroundTruth)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::cartographer::ground_truth::proto::Relation > relation_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fground_5ftruth_2fproto_2frelations_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fground_5ftruth_2fproto_2frelations_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fground_5ftruth_2fproto_2frelations_2eproto();

  void InitAsDefaultInstance();
  static GroundTruth* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Relation

// optional int64 timestamp1 = 1;
inline void Relation::clear_timestamp1() {
  timestamp1_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Relation::timestamp1() const {
  // @@protoc_insertion_point(field_get:cartographer.ground_truth.proto.Relation.timestamp1)
  return timestamp1_;
}
inline void Relation::set_timestamp1(::google::protobuf::int64 value) {
  
  timestamp1_ = value;
  // @@protoc_insertion_point(field_set:cartographer.ground_truth.proto.Relation.timestamp1)
}

// optional int64 timestamp2 = 2;
inline void Relation::clear_timestamp2() {
  timestamp2_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Relation::timestamp2() const {
  // @@protoc_insertion_point(field_get:cartographer.ground_truth.proto.Relation.timestamp2)
  return timestamp2_;
}
inline void Relation::set_timestamp2(::google::protobuf::int64 value) {
  
  timestamp2_ = value;
  // @@protoc_insertion_point(field_set:cartographer.ground_truth.proto.Relation.timestamp2)
}

// optional .cartographer.transform.proto.Rigid3d expected = 3;
inline bool Relation::has_expected() const {
  return !_is_default_instance_ && expected_ != NULL;
}
inline void Relation::clear_expected() {
  if (GetArenaNoVirtual() == NULL && expected_ != NULL) delete expected_;
  expected_ = NULL;
}
inline const ::cartographer::transform::proto::Rigid3d& Relation::expected() const {
  // @@protoc_insertion_point(field_get:cartographer.ground_truth.proto.Relation.expected)
  return expected_ != NULL ? *expected_ : *default_instance_->expected_;
}
inline ::cartographer::transform::proto::Rigid3d* Relation::mutable_expected() {
  
  if (expected_ == NULL) {
    expected_ = new ::cartographer::transform::proto::Rigid3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.ground_truth.proto.Relation.expected)
  return expected_;
}
inline ::cartographer::transform::proto::Rigid3d* Relation::release_expected() {
  // @@protoc_insertion_point(field_release:cartographer.ground_truth.proto.Relation.expected)
  
  ::cartographer::transform::proto::Rigid3d* temp = expected_;
  expected_ = NULL;
  return temp;
}
inline void Relation::set_allocated_expected(::cartographer::transform::proto::Rigid3d* expected) {
  delete expected_;
  expected_ = expected;
  if (expected) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.ground_truth.proto.Relation.expected)
}

// optional double covered_distance = 4;
inline void Relation::clear_covered_distance() {
  covered_distance_ = 0;
}
inline double Relation::covered_distance() const {
  // @@protoc_insertion_point(field_get:cartographer.ground_truth.proto.Relation.covered_distance)
  return covered_distance_;
}
inline void Relation::set_covered_distance(double value) {
  
  covered_distance_ = value;
  // @@protoc_insertion_point(field_set:cartographer.ground_truth.proto.Relation.covered_distance)
}

// -------------------------------------------------------------------

// GroundTruth

// repeated .cartographer.ground_truth.proto.Relation relation = 1;
inline int GroundTruth::relation_size() const {
  return relation_.size();
}
inline void GroundTruth::clear_relation() {
  relation_.Clear();
}
inline const ::cartographer::ground_truth::proto::Relation& GroundTruth::relation(int index) const {
  // @@protoc_insertion_point(field_get:cartographer.ground_truth.proto.GroundTruth.relation)
  return relation_.Get(index);
}
inline ::cartographer::ground_truth::proto::Relation* GroundTruth::mutable_relation(int index) {
  // @@protoc_insertion_point(field_mutable:cartographer.ground_truth.proto.GroundTruth.relation)
  return relation_.Mutable(index);
}
inline ::cartographer::ground_truth::proto::Relation* GroundTruth::add_relation() {
  // @@protoc_insertion_point(field_add:cartographer.ground_truth.proto.GroundTruth.relation)
  return relation_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::cartographer::ground_truth::proto::Relation >*
GroundTruth::mutable_relation() {
  // @@protoc_insertion_point(field_mutable_list:cartographer.ground_truth.proto.GroundTruth.relation)
  return &relation_;
}
inline const ::google::protobuf::RepeatedPtrField< ::cartographer::ground_truth::proto::Relation >&
GroundTruth::relation() const {
  // @@protoc_insertion_point(field_list:cartographer.ground_truth.proto.GroundTruth.relation)
  return relation_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace ground_truth
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fground_5ftruth_2fproto_2frelations_2eproto__INCLUDED
