// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/sensor/proto/adaptive_voxel_filter_options.proto

#ifndef PROTOBUF_cartographer_2fsensor_2fproto_2fadaptive_5fvoxel_5ffilter_5foptions_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fsensor_2fproto_2fadaptive_5fvoxel_5ffilter_5foptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace sensor {
namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_cartographer_2fsensor_2fproto_2fadaptive_5fvoxel_5ffilter_5foptions_2eproto();
void protobuf_AssignDesc_cartographer_2fsensor_2fproto_2fadaptive_5fvoxel_5ffilter_5foptions_2eproto();
void protobuf_ShutdownFile_cartographer_2fsensor_2fproto_2fadaptive_5fvoxel_5ffilter_5foptions_2eproto();

class AdaptiveVoxelFilterOptions;

// ===================================================================

class AdaptiveVoxelFilterOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.sensor.proto.AdaptiveVoxelFilterOptions) */ {
 public:
  AdaptiveVoxelFilterOptions();
  virtual ~AdaptiveVoxelFilterOptions();

  AdaptiveVoxelFilterOptions(const AdaptiveVoxelFilterOptions& from);

  inline AdaptiveVoxelFilterOptions& operator=(const AdaptiveVoxelFilterOptions& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AdaptiveVoxelFilterOptions& default_instance();

  void Swap(AdaptiveVoxelFilterOptions* other);

  // implements Message ----------------------------------------------

  inline AdaptiveVoxelFilterOptions* New() const { return New(NULL); }

  AdaptiveVoxelFilterOptions* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AdaptiveVoxelFilterOptions& from);
  void MergeFrom(const AdaptiveVoxelFilterOptions& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AdaptiveVoxelFilterOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float max_length = 1;
  void clear_max_length();
  static const int kMaxLengthFieldNumber = 1;
  float max_length() const;
  void set_max_length(float value);

  // optional float min_num_points = 2;
  void clear_min_num_points();
  static const int kMinNumPointsFieldNumber = 2;
  float min_num_points() const;
  void set_min_num_points(float value);

  // optional float max_range = 3;
  void clear_max_range();
  static const int kMaxRangeFieldNumber = 3;
  float max_range() const;
  void set_max_range(float value);

  // @@protoc_insertion_point(class_scope:cartographer.sensor.proto.AdaptiveVoxelFilterOptions)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float max_length_;
  float min_num_points_;
  float max_range_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fsensor_2fproto_2fadaptive_5fvoxel_5ffilter_5foptions_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fsensor_2fproto_2fadaptive_5fvoxel_5ffilter_5foptions_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fsensor_2fproto_2fadaptive_5fvoxel_5ffilter_5foptions_2eproto();

  void InitAsDefaultInstance();
  static AdaptiveVoxelFilterOptions* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// AdaptiveVoxelFilterOptions

// optional float max_length = 1;
inline void AdaptiveVoxelFilterOptions::clear_max_length() {
  max_length_ = 0;
}
inline float AdaptiveVoxelFilterOptions::max_length() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.AdaptiveVoxelFilterOptions.max_length)
  return max_length_;
}
inline void AdaptiveVoxelFilterOptions::set_max_length(float value) {
  
  max_length_ = value;
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.AdaptiveVoxelFilterOptions.max_length)
}

// optional float min_num_points = 2;
inline void AdaptiveVoxelFilterOptions::clear_min_num_points() {
  min_num_points_ = 0;
}
inline float AdaptiveVoxelFilterOptions::min_num_points() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.AdaptiveVoxelFilterOptions.min_num_points)
  return min_num_points_;
}
inline void AdaptiveVoxelFilterOptions::set_min_num_points(float value) {
  
  min_num_points_ = value;
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.AdaptiveVoxelFilterOptions.min_num_points)
}

// optional float max_range = 3;
inline void AdaptiveVoxelFilterOptions::clear_max_range() {
  max_range_ = 0;
}
inline float AdaptiveVoxelFilterOptions::max_range() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.AdaptiveVoxelFilterOptions.max_range)
  return max_range_;
}
inline void AdaptiveVoxelFilterOptions::set_max_range(float value) {
  
  max_range_ = value;
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.AdaptiveVoxelFilterOptions.max_range)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace sensor
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fsensor_2fproto_2fadaptive_5fvoxel_5ffilter_5foptions_2eproto__INCLUDED
