// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/2d/cell_limits.proto

#ifndef PROTOBUF_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace mapping {
namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto();
void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto();
void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto();

class CellLimits;

// ===================================================================

class CellLimits : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.CellLimits) */ {
 public:
  CellLimits();
  virtual ~CellLimits();

  CellLimits(const CellLimits& from);

  inline CellLimits& operator=(const CellLimits& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CellLimits& default_instance();

  void Swap(CellLimits* other);

  // implements Message ----------------------------------------------

  inline CellLimits* New() const { return New(NULL); }

  CellLimits* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CellLimits& from);
  void MergeFrom(const CellLimits& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CellLimits* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 num_x_cells = 1;
  void clear_num_x_cells();
  static const int kNumXCellsFieldNumber = 1;
  ::google::protobuf::int32 num_x_cells() const;
  void set_num_x_cells(::google::protobuf::int32 value);

  // optional int32 num_y_cells = 2;
  void clear_num_y_cells();
  static const int kNumYCellsFieldNumber = 2;
  ::google::protobuf::int32 num_y_cells() const;
  void set_num_y_cells(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.CellLimits)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 num_x_cells_;
  ::google::protobuf::int32 num_y_cells_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto();

  void InitAsDefaultInstance();
  static CellLimits* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CellLimits

// optional int32 num_x_cells = 1;
inline void CellLimits::clear_num_x_cells() {
  num_x_cells_ = 0;
}
inline ::google::protobuf::int32 CellLimits::num_x_cells() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.CellLimits.num_x_cells)
  return num_x_cells_;
}
inline void CellLimits::set_num_x_cells(::google::protobuf::int32 value) {
  
  num_x_cells_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.CellLimits.num_x_cells)
}

// optional int32 num_y_cells = 2;
inline void CellLimits::clear_num_y_cells() {
  num_y_cells_ = 0;
}
inline ::google::protobuf::int32 CellLimits::num_y_cells() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.CellLimits.num_y_cells)
  return num_y_cells_;
}
inline void CellLimits::set_num_y_cells(::google::protobuf::int32 value) {
  
  num_y_cells_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.CellLimits.num_y_cells)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_2fproto_2f2d_2fcell_5flimits_2eproto__INCLUDED
