// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/motion_filter_options.proto

#ifndef PROTOBUF_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace mapping {
namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto();
void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto();
void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto();

class MotionFilterOptions;

// ===================================================================

class MotionFilterOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.MotionFilterOptions) */ {
 public:
  MotionFilterOptions();
  virtual ~MotionFilterOptions();

  MotionFilterOptions(const MotionFilterOptions& from);

  inline MotionFilterOptions& operator=(const MotionFilterOptions& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MotionFilterOptions& default_instance();

  void Swap(MotionFilterOptions* other);

  // implements Message ----------------------------------------------

  inline MotionFilterOptions* New() const { return New(NULL); }

  MotionFilterOptions* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MotionFilterOptions& from);
  void MergeFrom(const MotionFilterOptions& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MotionFilterOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double max_time_seconds = 1;
  void clear_max_time_seconds();
  static const int kMaxTimeSecondsFieldNumber = 1;
  double max_time_seconds() const;
  void set_max_time_seconds(double value);

  // optional double max_distance_meters = 2;
  void clear_max_distance_meters();
  static const int kMaxDistanceMetersFieldNumber = 2;
  double max_distance_meters() const;
  void set_max_distance_meters(double value);

  // optional double max_angle_radians = 3;
  void clear_max_angle_radians();
  static const int kMaxAngleRadiansFieldNumber = 3;
  double max_angle_radians() const;
  void set_max_angle_radians(double value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.MotionFilterOptions)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double max_time_seconds_;
  double max_distance_meters_;
  double max_angle_radians_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto();

  void InitAsDefaultInstance();
  static MotionFilterOptions* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MotionFilterOptions

// optional double max_time_seconds = 1;
inline void MotionFilterOptions::clear_max_time_seconds() {
  max_time_seconds_ = 0;
}
inline double MotionFilterOptions::max_time_seconds() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.MotionFilterOptions.max_time_seconds)
  return max_time_seconds_;
}
inline void MotionFilterOptions::set_max_time_seconds(double value) {
  
  max_time_seconds_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.MotionFilterOptions.max_time_seconds)
}

// optional double max_distance_meters = 2;
inline void MotionFilterOptions::clear_max_distance_meters() {
  max_distance_meters_ = 0;
}
inline double MotionFilterOptions::max_distance_meters() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.MotionFilterOptions.max_distance_meters)
  return max_distance_meters_;
}
inline void MotionFilterOptions::set_max_distance_meters(double value) {
  
  max_distance_meters_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.MotionFilterOptions.max_distance_meters)
}

// optional double max_angle_radians = 3;
inline void MotionFilterOptions::clear_max_angle_radians() {
  max_angle_radians_ = 0;
}
inline double MotionFilterOptions::max_angle_radians() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.MotionFilterOptions.max_angle_radians)
  return max_angle_radians_;
}
inline void MotionFilterOptions::set_max_angle_radians(double value) {
  
  max_angle_radians_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.MotionFilterOptions.max_angle_radians)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto__INCLUDED
