// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/serialization.proto

#ifndef PROTOBUF_cartographer_2fmapping_2fproto_2fserialization_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_2fproto_2fserialization_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "cartographer/mapping/proto/pose_graph.pb.h"
#include "cartographer/mapping/proto/submap.pb.h"
#include "cartographer/mapping/proto/trajectory_node_data.pb.h"
#include "cartographer/sensor/proto/sensor.pb.h"
#include "cartographer/mapping/proto/trajectory_builder_options.pb.h"
#include "cartographer/transform/proto/transform.pb.h"
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace mapping {
namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fserialization_2eproto();

class FixedFramePoseData;
class ImuData;
class LandmarkData;
class LocalSlamResultData;
class Node;
class OdometryData;
class SerializationHeader;
class SerializedData;
class Submap;
class TrajectoryData;

// ===================================================================

class Submap : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.Submap) */ {
 public:
  Submap();
  virtual ~Submap();

  Submap(const Submap& from);

  inline Submap& operator=(const Submap& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Submap& default_instance();

  void Swap(Submap* other);

  // implements Message ----------------------------------------------

  inline Submap* New() const { return New(NULL); }

  Submap* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Submap& from);
  void MergeFrom(const Submap& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Submap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cartographer.mapping.proto.SubmapId submap_id = 1;
  bool has_submap_id() const;
  void clear_submap_id();
  static const int kSubmapIdFieldNumber = 1;
  const ::cartographer::mapping::proto::SubmapId& submap_id() const;
  ::cartographer::mapping::proto::SubmapId* mutable_submap_id();
  ::cartographer::mapping::proto::SubmapId* release_submap_id();
  void set_allocated_submap_id(::cartographer::mapping::proto::SubmapId* submap_id);

  // optional .cartographer.mapping.proto.Submap2D submap_2d = 2;
  bool has_submap_2d() const;
  void clear_submap_2d();
  static const int kSubmap2DFieldNumber = 2;
  const ::cartographer::mapping::proto::Submap2D& submap_2d() const;
  ::cartographer::mapping::proto::Submap2D* mutable_submap_2d();
  ::cartographer::mapping::proto::Submap2D* release_submap_2d();
  void set_allocated_submap_2d(::cartographer::mapping::proto::Submap2D* submap_2d);

  // optional .cartographer.mapping.proto.Submap3D submap_3d = 3;
  bool has_submap_3d() const;
  void clear_submap_3d();
  static const int kSubmap3DFieldNumber = 3;
  const ::cartographer::mapping::proto::Submap3D& submap_3d() const;
  ::cartographer::mapping::proto::Submap3D* mutable_submap_3d();
  ::cartographer::mapping::proto::Submap3D* release_submap_3d();
  void set_allocated_submap_3d(::cartographer::mapping::proto::Submap3D* submap_3d);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.Submap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::cartographer::mapping::proto::SubmapId* submap_id_;
  ::cartographer::mapping::proto::Submap2D* submap_2d_;
  ::cartographer::mapping::proto::Submap3D* submap_3d_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fserialization_2eproto();

  void InitAsDefaultInstance();
  static Submap* default_instance_;
};
// -------------------------------------------------------------------

class Node : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.Node) */ {
 public:
  Node();
  virtual ~Node();

  Node(const Node& from);

  inline Node& operator=(const Node& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Node& default_instance();

  void Swap(Node* other);

  // implements Message ----------------------------------------------

  inline Node* New() const { return New(NULL); }

  Node* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Node& from);
  void MergeFrom(const Node& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Node* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cartographer.mapping.proto.NodeId node_id = 1;
  bool has_node_id() const;
  void clear_node_id();
  static const int kNodeIdFieldNumber = 1;
  const ::cartographer::mapping::proto::NodeId& node_id() const;
  ::cartographer::mapping::proto::NodeId* mutable_node_id();
  ::cartographer::mapping::proto::NodeId* release_node_id();
  void set_allocated_node_id(::cartographer::mapping::proto::NodeId* node_id);

  // optional .cartographer.mapping.proto.TrajectoryNodeData node_data = 5;
  bool has_node_data() const;
  void clear_node_data();
  static const int kNodeDataFieldNumber = 5;
  const ::cartographer::mapping::proto::TrajectoryNodeData& node_data() const;
  ::cartographer::mapping::proto::TrajectoryNodeData* mutable_node_data();
  ::cartographer::mapping::proto::TrajectoryNodeData* release_node_data();
  void set_allocated_node_data(::cartographer::mapping::proto::TrajectoryNodeData* node_data);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.Node)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::cartographer::mapping::proto::NodeId* node_id_;
  ::cartographer::mapping::proto::TrajectoryNodeData* node_data_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fserialization_2eproto();

  void InitAsDefaultInstance();
  static Node* default_instance_;
};
// -------------------------------------------------------------------

class ImuData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.ImuData) */ {
 public:
  ImuData();
  virtual ~ImuData();

  ImuData(const ImuData& from);

  inline ImuData& operator=(const ImuData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ImuData& default_instance();

  void Swap(ImuData* other);

  // implements Message ----------------------------------------------

  inline ImuData* New() const { return New(NULL); }

  ImuData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ImuData& from);
  void MergeFrom(const ImuData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ImuData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 trajectory_id = 1;
  void clear_trajectory_id();
  static const int kTrajectoryIdFieldNumber = 1;
  ::google::protobuf::int32 trajectory_id() const;
  void set_trajectory_id(::google::protobuf::int32 value);

  // optional .cartographer.sensor.proto.ImuData imu_data = 2;
  bool has_imu_data() const;
  void clear_imu_data();
  static const int kImuDataFieldNumber = 2;
  const ::cartographer::sensor::proto::ImuData& imu_data() const;
  ::cartographer::sensor::proto::ImuData* mutable_imu_data();
  ::cartographer::sensor::proto::ImuData* release_imu_data();
  void set_allocated_imu_data(::cartographer::sensor::proto::ImuData* imu_data);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.ImuData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::cartographer::sensor::proto::ImuData* imu_data_;
  ::google::protobuf::int32 trajectory_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fserialization_2eproto();

  void InitAsDefaultInstance();
  static ImuData* default_instance_;
};
// -------------------------------------------------------------------

class OdometryData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.OdometryData) */ {
 public:
  OdometryData();
  virtual ~OdometryData();

  OdometryData(const OdometryData& from);

  inline OdometryData& operator=(const OdometryData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OdometryData& default_instance();

  void Swap(OdometryData* other);

  // implements Message ----------------------------------------------

  inline OdometryData* New() const { return New(NULL); }

  OdometryData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OdometryData& from);
  void MergeFrom(const OdometryData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OdometryData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 trajectory_id = 1;
  void clear_trajectory_id();
  static const int kTrajectoryIdFieldNumber = 1;
  ::google::protobuf::int32 trajectory_id() const;
  void set_trajectory_id(::google::protobuf::int32 value);

  // optional .cartographer.sensor.proto.OdometryData odometry_data = 2;
  bool has_odometry_data() const;
  void clear_odometry_data();
  static const int kOdometryDataFieldNumber = 2;
  const ::cartographer::sensor::proto::OdometryData& odometry_data() const;
  ::cartographer::sensor::proto::OdometryData* mutable_odometry_data();
  ::cartographer::sensor::proto::OdometryData* release_odometry_data();
  void set_allocated_odometry_data(::cartographer::sensor::proto::OdometryData* odometry_data);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.OdometryData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::cartographer::sensor::proto::OdometryData* odometry_data_;
  ::google::protobuf::int32 trajectory_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fserialization_2eproto();

  void InitAsDefaultInstance();
  static OdometryData* default_instance_;
};
// -------------------------------------------------------------------

class FixedFramePoseData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.FixedFramePoseData) */ {
 public:
  FixedFramePoseData();
  virtual ~FixedFramePoseData();

  FixedFramePoseData(const FixedFramePoseData& from);

  inline FixedFramePoseData& operator=(const FixedFramePoseData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FixedFramePoseData& default_instance();

  void Swap(FixedFramePoseData* other);

  // implements Message ----------------------------------------------

  inline FixedFramePoseData* New() const { return New(NULL); }

  FixedFramePoseData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FixedFramePoseData& from);
  void MergeFrom(const FixedFramePoseData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FixedFramePoseData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 trajectory_id = 1;
  void clear_trajectory_id();
  static const int kTrajectoryIdFieldNumber = 1;
  ::google::protobuf::int32 trajectory_id() const;
  void set_trajectory_id(::google::protobuf::int32 value);

  // optional .cartographer.sensor.proto.FixedFramePoseData fixed_frame_pose_data = 2;
  bool has_fixed_frame_pose_data() const;
  void clear_fixed_frame_pose_data();
  static const int kFixedFramePoseDataFieldNumber = 2;
  const ::cartographer::sensor::proto::FixedFramePoseData& fixed_frame_pose_data() const;
  ::cartographer::sensor::proto::FixedFramePoseData* mutable_fixed_frame_pose_data();
  ::cartographer::sensor::proto::FixedFramePoseData* release_fixed_frame_pose_data();
  void set_allocated_fixed_frame_pose_data(::cartographer::sensor::proto::FixedFramePoseData* fixed_frame_pose_data);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.FixedFramePoseData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::cartographer::sensor::proto::FixedFramePoseData* fixed_frame_pose_data_;
  ::google::protobuf::int32 trajectory_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fserialization_2eproto();

  void InitAsDefaultInstance();
  static FixedFramePoseData* default_instance_;
};
// -------------------------------------------------------------------

class LandmarkData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.LandmarkData) */ {
 public:
  LandmarkData();
  virtual ~LandmarkData();

  LandmarkData(const LandmarkData& from);

  inline LandmarkData& operator=(const LandmarkData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LandmarkData& default_instance();

  void Swap(LandmarkData* other);

  // implements Message ----------------------------------------------

  inline LandmarkData* New() const { return New(NULL); }

  LandmarkData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LandmarkData& from);
  void MergeFrom(const LandmarkData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LandmarkData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 trajectory_id = 1;
  void clear_trajectory_id();
  static const int kTrajectoryIdFieldNumber = 1;
  ::google::protobuf::int32 trajectory_id() const;
  void set_trajectory_id(::google::protobuf::int32 value);

  // optional .cartographer.sensor.proto.LandmarkData landmark_data = 2;
  bool has_landmark_data() const;
  void clear_landmark_data();
  static const int kLandmarkDataFieldNumber = 2;
  const ::cartographer::sensor::proto::LandmarkData& landmark_data() const;
  ::cartographer::sensor::proto::LandmarkData* mutable_landmark_data();
  ::cartographer::sensor::proto::LandmarkData* release_landmark_data();
  void set_allocated_landmark_data(::cartographer::sensor::proto::LandmarkData* landmark_data);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.LandmarkData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::cartographer::sensor::proto::LandmarkData* landmark_data_;
  ::google::protobuf::int32 trajectory_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fserialization_2eproto();

  void InitAsDefaultInstance();
  static LandmarkData* default_instance_;
};
// -------------------------------------------------------------------

class TrajectoryData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.TrajectoryData) */ {
 public:
  TrajectoryData();
  virtual ~TrajectoryData();

  TrajectoryData(const TrajectoryData& from);

  inline TrajectoryData& operator=(const TrajectoryData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrajectoryData& default_instance();

  void Swap(TrajectoryData* other);

  // implements Message ----------------------------------------------

  inline TrajectoryData* New() const { return New(NULL); }

  TrajectoryData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TrajectoryData& from);
  void MergeFrom(const TrajectoryData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TrajectoryData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 trajectory_id = 1;
  void clear_trajectory_id();
  static const int kTrajectoryIdFieldNumber = 1;
  ::google::protobuf::int32 trajectory_id() const;
  void set_trajectory_id(::google::protobuf::int32 value);

  // optional double gravity_constant = 2;
  void clear_gravity_constant();
  static const int kGravityConstantFieldNumber = 2;
  double gravity_constant() const;
  void set_gravity_constant(double value);

  // optional .cartographer.transform.proto.Quaterniond imu_calibration = 3;
  bool has_imu_calibration() const;
  void clear_imu_calibration();
  static const int kImuCalibrationFieldNumber = 3;
  const ::cartographer::transform::proto::Quaterniond& imu_calibration() const;
  ::cartographer::transform::proto::Quaterniond* mutable_imu_calibration();
  ::cartographer::transform::proto::Quaterniond* release_imu_calibration();
  void set_allocated_imu_calibration(::cartographer::transform::proto::Quaterniond* imu_calibration);

  // optional .cartographer.transform.proto.Rigid3d fixed_frame_origin_in_map = 4;
  bool has_fixed_frame_origin_in_map() const;
  void clear_fixed_frame_origin_in_map();
  static const int kFixedFrameOriginInMapFieldNumber = 4;
  const ::cartographer::transform::proto::Rigid3d& fixed_frame_origin_in_map() const;
  ::cartographer::transform::proto::Rigid3d* mutable_fixed_frame_origin_in_map();
  ::cartographer::transform::proto::Rigid3d* release_fixed_frame_origin_in_map();
  void set_allocated_fixed_frame_origin_in_map(::cartographer::transform::proto::Rigid3d* fixed_frame_origin_in_map);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.TrajectoryData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double gravity_constant_;
  ::cartographer::transform::proto::Quaterniond* imu_calibration_;
  ::cartographer::transform::proto::Rigid3d* fixed_frame_origin_in_map_;
  ::google::protobuf::int32 trajectory_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fserialization_2eproto();

  void InitAsDefaultInstance();
  static TrajectoryData* default_instance_;
};
// -------------------------------------------------------------------

class LocalSlamResultData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.LocalSlamResultData) */ {
 public:
  LocalSlamResultData();
  virtual ~LocalSlamResultData();

  LocalSlamResultData(const LocalSlamResultData& from);

  inline LocalSlamResultData& operator=(const LocalSlamResultData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LocalSlamResultData& default_instance();

  void Swap(LocalSlamResultData* other);

  // implements Message ----------------------------------------------

  inline LocalSlamResultData* New() const { return New(NULL); }

  LocalSlamResultData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LocalSlamResultData& from);
  void MergeFrom(const LocalSlamResultData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LocalSlamResultData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // optional .cartographer.mapping.proto.TrajectoryNodeData node_data = 2;
  bool has_node_data() const;
  void clear_node_data();
  static const int kNodeDataFieldNumber = 2;
  const ::cartographer::mapping::proto::TrajectoryNodeData& node_data() const;
  ::cartographer::mapping::proto::TrajectoryNodeData* mutable_node_data();
  ::cartographer::mapping::proto::TrajectoryNodeData* release_node_data();
  void set_allocated_node_data(::cartographer::mapping::proto::TrajectoryNodeData* node_data);

  // repeated .cartographer.mapping.proto.Submap submaps = 3;
  int submaps_size() const;
  void clear_submaps();
  static const int kSubmapsFieldNumber = 3;
  const ::cartographer::mapping::proto::Submap& submaps(int index) const;
  ::cartographer::mapping::proto::Submap* mutable_submaps(int index);
  ::cartographer::mapping::proto::Submap* add_submaps();
  ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::Submap >*
      mutable_submaps();
  const ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::Submap >&
      submaps() const;

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.LocalSlamResultData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 timestamp_;
  ::cartographer::mapping::proto::TrajectoryNodeData* node_data_;
  ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::Submap > submaps_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fserialization_2eproto();

  void InitAsDefaultInstance();
  static LocalSlamResultData* default_instance_;
};
// -------------------------------------------------------------------

class SerializationHeader : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.SerializationHeader) */ {
 public:
  SerializationHeader();
  virtual ~SerializationHeader();

  SerializationHeader(const SerializationHeader& from);

  inline SerializationHeader& operator=(const SerializationHeader& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SerializationHeader& default_instance();

  void Swap(SerializationHeader* other);

  // implements Message ----------------------------------------------

  inline SerializationHeader* New() const { return New(NULL); }

  SerializationHeader* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SerializationHeader& from);
  void MergeFrom(const SerializationHeader& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SerializationHeader* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 format_version = 1;
  void clear_format_version();
  static const int kFormatVersionFieldNumber = 1;
  ::google::protobuf::uint32 format_version() const;
  void set_format_version(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.SerializationHeader)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 format_version_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fserialization_2eproto();

  void InitAsDefaultInstance();
  static SerializationHeader* default_instance_;
};
// -------------------------------------------------------------------

class SerializedData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.SerializedData) */ {
 public:
  SerializedData();
  virtual ~SerializedData();

  SerializedData(const SerializedData& from);

  inline SerializedData& operator=(const SerializedData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SerializedData& default_instance();

  enum DataCase {
    kPoseGraph = 1,
    kAllTrajectoryBuilderOptions = 2,
    kSubmap = 3,
    kNode = 4,
    kTrajectoryData = 5,
    kImuData = 6,
    kOdometryData = 7,
    kFixedFramePoseData = 8,
    kLandmarkData = 9,
    DATA_NOT_SET = 0,
  };

  void Swap(SerializedData* other);

  // implements Message ----------------------------------------------

  inline SerializedData* New() const { return New(NULL); }

  SerializedData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SerializedData& from);
  void MergeFrom(const SerializedData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SerializedData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cartographer.mapping.proto.PoseGraph pose_graph = 1;
  bool has_pose_graph() const;
  void clear_pose_graph();
  static const int kPoseGraphFieldNumber = 1;
  const ::cartographer::mapping::proto::PoseGraph& pose_graph() const;
  ::cartographer::mapping::proto::PoseGraph* mutable_pose_graph();
  ::cartographer::mapping::proto::PoseGraph* release_pose_graph();
  void set_allocated_pose_graph(::cartographer::mapping::proto::PoseGraph* pose_graph);

  // optional .cartographer.mapping.proto.AllTrajectoryBuilderOptions all_trajectory_builder_options = 2;
  bool has_all_trajectory_builder_options() const;
  void clear_all_trajectory_builder_options();
  static const int kAllTrajectoryBuilderOptionsFieldNumber = 2;
  const ::cartographer::mapping::proto::AllTrajectoryBuilderOptions& all_trajectory_builder_options() const;
  ::cartographer::mapping::proto::AllTrajectoryBuilderOptions* mutable_all_trajectory_builder_options();
  ::cartographer::mapping::proto::AllTrajectoryBuilderOptions* release_all_trajectory_builder_options();
  void set_allocated_all_trajectory_builder_options(::cartographer::mapping::proto::AllTrajectoryBuilderOptions* all_trajectory_builder_options);

  // optional .cartographer.mapping.proto.Submap submap = 3;
  bool has_submap() const;
  void clear_submap();
  static const int kSubmapFieldNumber = 3;
  const ::cartographer::mapping::proto::Submap& submap() const;
  ::cartographer::mapping::proto::Submap* mutable_submap();
  ::cartographer::mapping::proto::Submap* release_submap();
  void set_allocated_submap(::cartographer::mapping::proto::Submap* submap);

  // optional .cartographer.mapping.proto.Node node = 4;
  bool has_node() const;
  void clear_node();
  static const int kNodeFieldNumber = 4;
  const ::cartographer::mapping::proto::Node& node() const;
  ::cartographer::mapping::proto::Node* mutable_node();
  ::cartographer::mapping::proto::Node* release_node();
  void set_allocated_node(::cartographer::mapping::proto::Node* node);

  // optional .cartographer.mapping.proto.TrajectoryData trajectory_data = 5;
  bool has_trajectory_data() const;
  void clear_trajectory_data();
  static const int kTrajectoryDataFieldNumber = 5;
  const ::cartographer::mapping::proto::TrajectoryData& trajectory_data() const;
  ::cartographer::mapping::proto::TrajectoryData* mutable_trajectory_data();
  ::cartographer::mapping::proto::TrajectoryData* release_trajectory_data();
  void set_allocated_trajectory_data(::cartographer::mapping::proto::TrajectoryData* trajectory_data);

  // optional .cartographer.mapping.proto.ImuData imu_data = 6;
  bool has_imu_data() const;
  void clear_imu_data();
  static const int kImuDataFieldNumber = 6;
  const ::cartographer::mapping::proto::ImuData& imu_data() const;
  ::cartographer::mapping::proto::ImuData* mutable_imu_data();
  ::cartographer::mapping::proto::ImuData* release_imu_data();
  void set_allocated_imu_data(::cartographer::mapping::proto::ImuData* imu_data);

  // optional .cartographer.mapping.proto.OdometryData odometry_data = 7;
  bool has_odometry_data() const;
  void clear_odometry_data();
  static const int kOdometryDataFieldNumber = 7;
  const ::cartographer::mapping::proto::OdometryData& odometry_data() const;
  ::cartographer::mapping::proto::OdometryData* mutable_odometry_data();
  ::cartographer::mapping::proto::OdometryData* release_odometry_data();
  void set_allocated_odometry_data(::cartographer::mapping::proto::OdometryData* odometry_data);

  // optional .cartographer.mapping.proto.FixedFramePoseData fixed_frame_pose_data = 8;
  bool has_fixed_frame_pose_data() const;
  void clear_fixed_frame_pose_data();
  static const int kFixedFramePoseDataFieldNumber = 8;
  const ::cartographer::mapping::proto::FixedFramePoseData& fixed_frame_pose_data() const;
  ::cartographer::mapping::proto::FixedFramePoseData* mutable_fixed_frame_pose_data();
  ::cartographer::mapping::proto::FixedFramePoseData* release_fixed_frame_pose_data();
  void set_allocated_fixed_frame_pose_data(::cartographer::mapping::proto::FixedFramePoseData* fixed_frame_pose_data);

  // optional .cartographer.mapping.proto.LandmarkData landmark_data = 9;
  bool has_landmark_data() const;
  void clear_landmark_data();
  static const int kLandmarkDataFieldNumber = 9;
  const ::cartographer::mapping::proto::LandmarkData& landmark_data() const;
  ::cartographer::mapping::proto::LandmarkData* mutable_landmark_data();
  ::cartographer::mapping::proto::LandmarkData* release_landmark_data();
  void set_allocated_landmark_data(::cartographer::mapping::proto::LandmarkData* landmark_data);

  DataCase data_case() const;
  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.SerializedData)
 private:
  inline void set_has_pose_graph();
  inline void set_has_all_trajectory_builder_options();
  inline void set_has_submap();
  inline void set_has_node();
  inline void set_has_trajectory_data();
  inline void set_has_imu_data();
  inline void set_has_odometry_data();
  inline void set_has_fixed_frame_pose_data();
  inline void set_has_landmark_data();

  inline bool has_data() const;
  void clear_data();
  inline void clear_has_data();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  union DataUnion {
    DataUnion() {}
    ::cartographer::mapping::proto::PoseGraph* pose_graph_;
    ::cartographer::mapping::proto::AllTrajectoryBuilderOptions* all_trajectory_builder_options_;
    ::cartographer::mapping::proto::Submap* submap_;
    ::cartographer::mapping::proto::Node* node_;
    ::cartographer::mapping::proto::TrajectoryData* trajectory_data_;
    ::cartographer::mapping::proto::ImuData* imu_data_;
    ::cartographer::mapping::proto::OdometryData* odometry_data_;
    ::cartographer::mapping::proto::FixedFramePoseData* fixed_frame_pose_data_;
    ::cartographer::mapping::proto::LandmarkData* landmark_data_;
  } data_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fserialization_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fserialization_2eproto();

  void InitAsDefaultInstance();
  static SerializedData* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Submap

// optional .cartographer.mapping.proto.SubmapId submap_id = 1;
inline bool Submap::has_submap_id() const {
  return !_is_default_instance_ && submap_id_ != NULL;
}
inline void Submap::clear_submap_id() {
  if (GetArenaNoVirtual() == NULL && submap_id_ != NULL) delete submap_id_;
  submap_id_ = NULL;
}
inline const ::cartographer::mapping::proto::SubmapId& Submap::submap_id() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap.submap_id)
  return submap_id_ != NULL ? *submap_id_ : *default_instance_->submap_id_;
}
inline ::cartographer::mapping::proto::SubmapId* Submap::mutable_submap_id() {
  
  if (submap_id_ == NULL) {
    submap_id_ = new ::cartographer::mapping::proto::SubmapId;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Submap.submap_id)
  return submap_id_;
}
inline ::cartographer::mapping::proto::SubmapId* Submap::release_submap_id() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Submap.submap_id)
  
  ::cartographer::mapping::proto::SubmapId* temp = submap_id_;
  submap_id_ = NULL;
  return temp;
}
inline void Submap::set_allocated_submap_id(::cartographer::mapping::proto::SubmapId* submap_id) {
  delete submap_id_;
  submap_id_ = submap_id;
  if (submap_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Submap.submap_id)
}

// optional .cartographer.mapping.proto.Submap2D submap_2d = 2;
inline bool Submap::has_submap_2d() const {
  return !_is_default_instance_ && submap_2d_ != NULL;
}
inline void Submap::clear_submap_2d() {
  if (GetArenaNoVirtual() == NULL && submap_2d_ != NULL) delete submap_2d_;
  submap_2d_ = NULL;
}
inline const ::cartographer::mapping::proto::Submap2D& Submap::submap_2d() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap.submap_2d)
  return submap_2d_ != NULL ? *submap_2d_ : *default_instance_->submap_2d_;
}
inline ::cartographer::mapping::proto::Submap2D* Submap::mutable_submap_2d() {
  
  if (submap_2d_ == NULL) {
    submap_2d_ = new ::cartographer::mapping::proto::Submap2D;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Submap.submap_2d)
  return submap_2d_;
}
inline ::cartographer::mapping::proto::Submap2D* Submap::release_submap_2d() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Submap.submap_2d)
  
  ::cartographer::mapping::proto::Submap2D* temp = submap_2d_;
  submap_2d_ = NULL;
  return temp;
}
inline void Submap::set_allocated_submap_2d(::cartographer::mapping::proto::Submap2D* submap_2d) {
  delete submap_2d_;
  submap_2d_ = submap_2d;
  if (submap_2d) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Submap.submap_2d)
}

// optional .cartographer.mapping.proto.Submap3D submap_3d = 3;
inline bool Submap::has_submap_3d() const {
  return !_is_default_instance_ && submap_3d_ != NULL;
}
inline void Submap::clear_submap_3d() {
  if (GetArenaNoVirtual() == NULL && submap_3d_ != NULL) delete submap_3d_;
  submap_3d_ = NULL;
}
inline const ::cartographer::mapping::proto::Submap3D& Submap::submap_3d() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Submap.submap_3d)
  return submap_3d_ != NULL ? *submap_3d_ : *default_instance_->submap_3d_;
}
inline ::cartographer::mapping::proto::Submap3D* Submap::mutable_submap_3d() {
  
  if (submap_3d_ == NULL) {
    submap_3d_ = new ::cartographer::mapping::proto::Submap3D;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Submap.submap_3d)
  return submap_3d_;
}
inline ::cartographer::mapping::proto::Submap3D* Submap::release_submap_3d() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Submap.submap_3d)
  
  ::cartographer::mapping::proto::Submap3D* temp = submap_3d_;
  submap_3d_ = NULL;
  return temp;
}
inline void Submap::set_allocated_submap_3d(::cartographer::mapping::proto::Submap3D* submap_3d) {
  delete submap_3d_;
  submap_3d_ = submap_3d;
  if (submap_3d) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Submap.submap_3d)
}

// -------------------------------------------------------------------

// Node

// optional .cartographer.mapping.proto.NodeId node_id = 1;
inline bool Node::has_node_id() const {
  return !_is_default_instance_ && node_id_ != NULL;
}
inline void Node::clear_node_id() {
  if (GetArenaNoVirtual() == NULL && node_id_ != NULL) delete node_id_;
  node_id_ = NULL;
}
inline const ::cartographer::mapping::proto::NodeId& Node::node_id() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Node.node_id)
  return node_id_ != NULL ? *node_id_ : *default_instance_->node_id_;
}
inline ::cartographer::mapping::proto::NodeId* Node::mutable_node_id() {
  
  if (node_id_ == NULL) {
    node_id_ = new ::cartographer::mapping::proto::NodeId;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Node.node_id)
  return node_id_;
}
inline ::cartographer::mapping::proto::NodeId* Node::release_node_id() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Node.node_id)
  
  ::cartographer::mapping::proto::NodeId* temp = node_id_;
  node_id_ = NULL;
  return temp;
}
inline void Node::set_allocated_node_id(::cartographer::mapping::proto::NodeId* node_id) {
  delete node_id_;
  node_id_ = node_id;
  if (node_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Node.node_id)
}

// optional .cartographer.mapping.proto.TrajectoryNodeData node_data = 5;
inline bool Node::has_node_data() const {
  return !_is_default_instance_ && node_data_ != NULL;
}
inline void Node::clear_node_data() {
  if (GetArenaNoVirtual() == NULL && node_data_ != NULL) delete node_data_;
  node_data_ = NULL;
}
inline const ::cartographer::mapping::proto::TrajectoryNodeData& Node::node_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Node.node_data)
  return node_data_ != NULL ? *node_data_ : *default_instance_->node_data_;
}
inline ::cartographer::mapping::proto::TrajectoryNodeData* Node::mutable_node_data() {
  
  if (node_data_ == NULL) {
    node_data_ = new ::cartographer::mapping::proto::TrajectoryNodeData;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Node.node_data)
  return node_data_;
}
inline ::cartographer::mapping::proto::TrajectoryNodeData* Node::release_node_data() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Node.node_data)
  
  ::cartographer::mapping::proto::TrajectoryNodeData* temp = node_data_;
  node_data_ = NULL;
  return temp;
}
inline void Node::set_allocated_node_data(::cartographer::mapping::proto::TrajectoryNodeData* node_data) {
  delete node_data_;
  node_data_ = node_data;
  if (node_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Node.node_data)
}

// -------------------------------------------------------------------

// ImuData

// optional int32 trajectory_id = 1;
inline void ImuData::clear_trajectory_id() {
  trajectory_id_ = 0;
}
inline ::google::protobuf::int32 ImuData::trajectory_id() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.ImuData.trajectory_id)
  return trajectory_id_;
}
inline void ImuData::set_trajectory_id(::google::protobuf::int32 value) {
  
  trajectory_id_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.ImuData.trajectory_id)
}

// optional .cartographer.sensor.proto.ImuData imu_data = 2;
inline bool ImuData::has_imu_data() const {
  return !_is_default_instance_ && imu_data_ != NULL;
}
inline void ImuData::clear_imu_data() {
  if (GetArenaNoVirtual() == NULL && imu_data_ != NULL) delete imu_data_;
  imu_data_ = NULL;
}
inline const ::cartographer::sensor::proto::ImuData& ImuData::imu_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.ImuData.imu_data)
  return imu_data_ != NULL ? *imu_data_ : *default_instance_->imu_data_;
}
inline ::cartographer::sensor::proto::ImuData* ImuData::mutable_imu_data() {
  
  if (imu_data_ == NULL) {
    imu_data_ = new ::cartographer::sensor::proto::ImuData;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.ImuData.imu_data)
  return imu_data_;
}
inline ::cartographer::sensor::proto::ImuData* ImuData::release_imu_data() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.ImuData.imu_data)
  
  ::cartographer::sensor::proto::ImuData* temp = imu_data_;
  imu_data_ = NULL;
  return temp;
}
inline void ImuData::set_allocated_imu_data(::cartographer::sensor::proto::ImuData* imu_data) {
  delete imu_data_;
  imu_data_ = imu_data;
  if (imu_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.ImuData.imu_data)
}

// -------------------------------------------------------------------

// OdometryData

// optional int32 trajectory_id = 1;
inline void OdometryData::clear_trajectory_id() {
  trajectory_id_ = 0;
}
inline ::google::protobuf::int32 OdometryData::trajectory_id() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.OdometryData.trajectory_id)
  return trajectory_id_;
}
inline void OdometryData::set_trajectory_id(::google::protobuf::int32 value) {
  
  trajectory_id_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.OdometryData.trajectory_id)
}

// optional .cartographer.sensor.proto.OdometryData odometry_data = 2;
inline bool OdometryData::has_odometry_data() const {
  return !_is_default_instance_ && odometry_data_ != NULL;
}
inline void OdometryData::clear_odometry_data() {
  if (GetArenaNoVirtual() == NULL && odometry_data_ != NULL) delete odometry_data_;
  odometry_data_ = NULL;
}
inline const ::cartographer::sensor::proto::OdometryData& OdometryData::odometry_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.OdometryData.odometry_data)
  return odometry_data_ != NULL ? *odometry_data_ : *default_instance_->odometry_data_;
}
inline ::cartographer::sensor::proto::OdometryData* OdometryData::mutable_odometry_data() {
  
  if (odometry_data_ == NULL) {
    odometry_data_ = new ::cartographer::sensor::proto::OdometryData;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.OdometryData.odometry_data)
  return odometry_data_;
}
inline ::cartographer::sensor::proto::OdometryData* OdometryData::release_odometry_data() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.OdometryData.odometry_data)
  
  ::cartographer::sensor::proto::OdometryData* temp = odometry_data_;
  odometry_data_ = NULL;
  return temp;
}
inline void OdometryData::set_allocated_odometry_data(::cartographer::sensor::proto::OdometryData* odometry_data) {
  delete odometry_data_;
  odometry_data_ = odometry_data;
  if (odometry_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.OdometryData.odometry_data)
}

// -------------------------------------------------------------------

// FixedFramePoseData

// optional int32 trajectory_id = 1;
inline void FixedFramePoseData::clear_trajectory_id() {
  trajectory_id_ = 0;
}
inline ::google::protobuf::int32 FixedFramePoseData::trajectory_id() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.FixedFramePoseData.trajectory_id)
  return trajectory_id_;
}
inline void FixedFramePoseData::set_trajectory_id(::google::protobuf::int32 value) {
  
  trajectory_id_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.FixedFramePoseData.trajectory_id)
}

// optional .cartographer.sensor.proto.FixedFramePoseData fixed_frame_pose_data = 2;
inline bool FixedFramePoseData::has_fixed_frame_pose_data() const {
  return !_is_default_instance_ && fixed_frame_pose_data_ != NULL;
}
inline void FixedFramePoseData::clear_fixed_frame_pose_data() {
  if (GetArenaNoVirtual() == NULL && fixed_frame_pose_data_ != NULL) delete fixed_frame_pose_data_;
  fixed_frame_pose_data_ = NULL;
}
inline const ::cartographer::sensor::proto::FixedFramePoseData& FixedFramePoseData::fixed_frame_pose_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.FixedFramePoseData.fixed_frame_pose_data)
  return fixed_frame_pose_data_ != NULL ? *fixed_frame_pose_data_ : *default_instance_->fixed_frame_pose_data_;
}
inline ::cartographer::sensor::proto::FixedFramePoseData* FixedFramePoseData::mutable_fixed_frame_pose_data() {
  
  if (fixed_frame_pose_data_ == NULL) {
    fixed_frame_pose_data_ = new ::cartographer::sensor::proto::FixedFramePoseData;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.FixedFramePoseData.fixed_frame_pose_data)
  return fixed_frame_pose_data_;
}
inline ::cartographer::sensor::proto::FixedFramePoseData* FixedFramePoseData::release_fixed_frame_pose_data() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.FixedFramePoseData.fixed_frame_pose_data)
  
  ::cartographer::sensor::proto::FixedFramePoseData* temp = fixed_frame_pose_data_;
  fixed_frame_pose_data_ = NULL;
  return temp;
}
inline void FixedFramePoseData::set_allocated_fixed_frame_pose_data(::cartographer::sensor::proto::FixedFramePoseData* fixed_frame_pose_data) {
  delete fixed_frame_pose_data_;
  fixed_frame_pose_data_ = fixed_frame_pose_data;
  if (fixed_frame_pose_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.FixedFramePoseData.fixed_frame_pose_data)
}

// -------------------------------------------------------------------

// LandmarkData

// optional int32 trajectory_id = 1;
inline void LandmarkData::clear_trajectory_id() {
  trajectory_id_ = 0;
}
inline ::google::protobuf::int32 LandmarkData::trajectory_id() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.LandmarkData.trajectory_id)
  return trajectory_id_;
}
inline void LandmarkData::set_trajectory_id(::google::protobuf::int32 value) {
  
  trajectory_id_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.LandmarkData.trajectory_id)
}

// optional .cartographer.sensor.proto.LandmarkData landmark_data = 2;
inline bool LandmarkData::has_landmark_data() const {
  return !_is_default_instance_ && landmark_data_ != NULL;
}
inline void LandmarkData::clear_landmark_data() {
  if (GetArenaNoVirtual() == NULL && landmark_data_ != NULL) delete landmark_data_;
  landmark_data_ = NULL;
}
inline const ::cartographer::sensor::proto::LandmarkData& LandmarkData::landmark_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.LandmarkData.landmark_data)
  return landmark_data_ != NULL ? *landmark_data_ : *default_instance_->landmark_data_;
}
inline ::cartographer::sensor::proto::LandmarkData* LandmarkData::mutable_landmark_data() {
  
  if (landmark_data_ == NULL) {
    landmark_data_ = new ::cartographer::sensor::proto::LandmarkData;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.LandmarkData.landmark_data)
  return landmark_data_;
}
inline ::cartographer::sensor::proto::LandmarkData* LandmarkData::release_landmark_data() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.LandmarkData.landmark_data)
  
  ::cartographer::sensor::proto::LandmarkData* temp = landmark_data_;
  landmark_data_ = NULL;
  return temp;
}
inline void LandmarkData::set_allocated_landmark_data(::cartographer::sensor::proto::LandmarkData* landmark_data) {
  delete landmark_data_;
  landmark_data_ = landmark_data;
  if (landmark_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.LandmarkData.landmark_data)
}

// -------------------------------------------------------------------

// TrajectoryData

// optional int32 trajectory_id = 1;
inline void TrajectoryData::clear_trajectory_id() {
  trajectory_id_ = 0;
}
inline ::google::protobuf::int32 TrajectoryData::trajectory_id() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TrajectoryData.trajectory_id)
  return trajectory_id_;
}
inline void TrajectoryData::set_trajectory_id(::google::protobuf::int32 value) {
  
  trajectory_id_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.TrajectoryData.trajectory_id)
}

// optional double gravity_constant = 2;
inline void TrajectoryData::clear_gravity_constant() {
  gravity_constant_ = 0;
}
inline double TrajectoryData::gravity_constant() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TrajectoryData.gravity_constant)
  return gravity_constant_;
}
inline void TrajectoryData::set_gravity_constant(double value) {
  
  gravity_constant_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.TrajectoryData.gravity_constant)
}

// optional .cartographer.transform.proto.Quaterniond imu_calibration = 3;
inline bool TrajectoryData::has_imu_calibration() const {
  return !_is_default_instance_ && imu_calibration_ != NULL;
}
inline void TrajectoryData::clear_imu_calibration() {
  if (GetArenaNoVirtual() == NULL && imu_calibration_ != NULL) delete imu_calibration_;
  imu_calibration_ = NULL;
}
inline const ::cartographer::transform::proto::Quaterniond& TrajectoryData::imu_calibration() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TrajectoryData.imu_calibration)
  return imu_calibration_ != NULL ? *imu_calibration_ : *default_instance_->imu_calibration_;
}
inline ::cartographer::transform::proto::Quaterniond* TrajectoryData::mutable_imu_calibration() {
  
  if (imu_calibration_ == NULL) {
    imu_calibration_ = new ::cartographer::transform::proto::Quaterniond;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.TrajectoryData.imu_calibration)
  return imu_calibration_;
}
inline ::cartographer::transform::proto::Quaterniond* TrajectoryData::release_imu_calibration() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.TrajectoryData.imu_calibration)
  
  ::cartographer::transform::proto::Quaterniond* temp = imu_calibration_;
  imu_calibration_ = NULL;
  return temp;
}
inline void TrajectoryData::set_allocated_imu_calibration(::cartographer::transform::proto::Quaterniond* imu_calibration) {
  delete imu_calibration_;
  imu_calibration_ = imu_calibration;
  if (imu_calibration) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.TrajectoryData.imu_calibration)
}

// optional .cartographer.transform.proto.Rigid3d fixed_frame_origin_in_map = 4;
inline bool TrajectoryData::has_fixed_frame_origin_in_map() const {
  return !_is_default_instance_ && fixed_frame_origin_in_map_ != NULL;
}
inline void TrajectoryData::clear_fixed_frame_origin_in_map() {
  if (GetArenaNoVirtual() == NULL && fixed_frame_origin_in_map_ != NULL) delete fixed_frame_origin_in_map_;
  fixed_frame_origin_in_map_ = NULL;
}
inline const ::cartographer::transform::proto::Rigid3d& TrajectoryData::fixed_frame_origin_in_map() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TrajectoryData.fixed_frame_origin_in_map)
  return fixed_frame_origin_in_map_ != NULL ? *fixed_frame_origin_in_map_ : *default_instance_->fixed_frame_origin_in_map_;
}
inline ::cartographer::transform::proto::Rigid3d* TrajectoryData::mutable_fixed_frame_origin_in_map() {
  
  if (fixed_frame_origin_in_map_ == NULL) {
    fixed_frame_origin_in_map_ = new ::cartographer::transform::proto::Rigid3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.TrajectoryData.fixed_frame_origin_in_map)
  return fixed_frame_origin_in_map_;
}
inline ::cartographer::transform::proto::Rigid3d* TrajectoryData::release_fixed_frame_origin_in_map() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.TrajectoryData.fixed_frame_origin_in_map)
  
  ::cartographer::transform::proto::Rigid3d* temp = fixed_frame_origin_in_map_;
  fixed_frame_origin_in_map_ = NULL;
  return temp;
}
inline void TrajectoryData::set_allocated_fixed_frame_origin_in_map(::cartographer::transform::proto::Rigid3d* fixed_frame_origin_in_map) {
  delete fixed_frame_origin_in_map_;
  fixed_frame_origin_in_map_ = fixed_frame_origin_in_map;
  if (fixed_frame_origin_in_map) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.TrajectoryData.fixed_frame_origin_in_map)
}

// -------------------------------------------------------------------

// LocalSlamResultData

// optional int64 timestamp = 1;
inline void LocalSlamResultData::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LocalSlamResultData::timestamp() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.LocalSlamResultData.timestamp)
  return timestamp_;
}
inline void LocalSlamResultData::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.LocalSlamResultData.timestamp)
}

// optional .cartographer.mapping.proto.TrajectoryNodeData node_data = 2;
inline bool LocalSlamResultData::has_node_data() const {
  return !_is_default_instance_ && node_data_ != NULL;
}
inline void LocalSlamResultData::clear_node_data() {
  if (GetArenaNoVirtual() == NULL && node_data_ != NULL) delete node_data_;
  node_data_ = NULL;
}
inline const ::cartographer::mapping::proto::TrajectoryNodeData& LocalSlamResultData::node_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.LocalSlamResultData.node_data)
  return node_data_ != NULL ? *node_data_ : *default_instance_->node_data_;
}
inline ::cartographer::mapping::proto::TrajectoryNodeData* LocalSlamResultData::mutable_node_data() {
  
  if (node_data_ == NULL) {
    node_data_ = new ::cartographer::mapping::proto::TrajectoryNodeData;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.LocalSlamResultData.node_data)
  return node_data_;
}
inline ::cartographer::mapping::proto::TrajectoryNodeData* LocalSlamResultData::release_node_data() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.LocalSlamResultData.node_data)
  
  ::cartographer::mapping::proto::TrajectoryNodeData* temp = node_data_;
  node_data_ = NULL;
  return temp;
}
inline void LocalSlamResultData::set_allocated_node_data(::cartographer::mapping::proto::TrajectoryNodeData* node_data) {
  delete node_data_;
  node_data_ = node_data;
  if (node_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.LocalSlamResultData.node_data)
}

// repeated .cartographer.mapping.proto.Submap submaps = 3;
inline int LocalSlamResultData::submaps_size() const {
  return submaps_.size();
}
inline void LocalSlamResultData::clear_submaps() {
  submaps_.Clear();
}
inline const ::cartographer::mapping::proto::Submap& LocalSlamResultData::submaps(int index) const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.LocalSlamResultData.submaps)
  return submaps_.Get(index);
}
inline ::cartographer::mapping::proto::Submap* LocalSlamResultData::mutable_submaps(int index) {
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.LocalSlamResultData.submaps)
  return submaps_.Mutable(index);
}
inline ::cartographer::mapping::proto::Submap* LocalSlamResultData::add_submaps() {
  // @@protoc_insertion_point(field_add:cartographer.mapping.proto.LocalSlamResultData.submaps)
  return submaps_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::Submap >*
LocalSlamResultData::mutable_submaps() {
  // @@protoc_insertion_point(field_mutable_list:cartographer.mapping.proto.LocalSlamResultData.submaps)
  return &submaps_;
}
inline const ::google::protobuf::RepeatedPtrField< ::cartographer::mapping::proto::Submap >&
LocalSlamResultData::submaps() const {
  // @@protoc_insertion_point(field_list:cartographer.mapping.proto.LocalSlamResultData.submaps)
  return submaps_;
}

// -------------------------------------------------------------------

// SerializationHeader

// optional uint32 format_version = 1;
inline void SerializationHeader::clear_format_version() {
  format_version_ = 0u;
}
inline ::google::protobuf::uint32 SerializationHeader::format_version() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.SerializationHeader.format_version)
  return format_version_;
}
inline void SerializationHeader::set_format_version(::google::protobuf::uint32 value) {
  
  format_version_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.SerializationHeader.format_version)
}

// -------------------------------------------------------------------

// SerializedData

// optional .cartographer.mapping.proto.PoseGraph pose_graph = 1;
inline bool SerializedData::has_pose_graph() const {
  return data_case() == kPoseGraph;
}
inline void SerializedData::set_has_pose_graph() {
  _oneof_case_[0] = kPoseGraph;
}
inline void SerializedData::clear_pose_graph() {
  if (has_pose_graph()) {
    delete data_.pose_graph_;
    clear_has_data();
  }
}
inline  const ::cartographer::mapping::proto::PoseGraph& SerializedData::pose_graph() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.SerializedData.pose_graph)
  return has_pose_graph()
      ? *data_.pose_graph_
      : ::cartographer::mapping::proto::PoseGraph::default_instance();
}
inline ::cartographer::mapping::proto::PoseGraph* SerializedData::mutable_pose_graph() {
  if (!has_pose_graph()) {
    clear_data();
    set_has_pose_graph();
    data_.pose_graph_ = new ::cartographer::mapping::proto::PoseGraph;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.SerializedData.pose_graph)
  return data_.pose_graph_;
}
inline ::cartographer::mapping::proto::PoseGraph* SerializedData::release_pose_graph() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.SerializedData.pose_graph)
  if (has_pose_graph()) {
    clear_has_data();
    ::cartographer::mapping::proto::PoseGraph* temp = data_.pose_graph_;
    data_.pose_graph_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void SerializedData::set_allocated_pose_graph(::cartographer::mapping::proto::PoseGraph* pose_graph) {
  clear_data();
  if (pose_graph) {
    set_has_pose_graph();
    data_.pose_graph_ = pose_graph;
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.SerializedData.pose_graph)
}

// optional .cartographer.mapping.proto.AllTrajectoryBuilderOptions all_trajectory_builder_options = 2;
inline bool SerializedData::has_all_trajectory_builder_options() const {
  return data_case() == kAllTrajectoryBuilderOptions;
}
inline void SerializedData::set_has_all_trajectory_builder_options() {
  _oneof_case_[0] = kAllTrajectoryBuilderOptions;
}
inline void SerializedData::clear_all_trajectory_builder_options() {
  if (has_all_trajectory_builder_options()) {
    delete data_.all_trajectory_builder_options_;
    clear_has_data();
  }
}
inline  const ::cartographer::mapping::proto::AllTrajectoryBuilderOptions& SerializedData::all_trajectory_builder_options() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.SerializedData.all_trajectory_builder_options)
  return has_all_trajectory_builder_options()
      ? *data_.all_trajectory_builder_options_
      : ::cartographer::mapping::proto::AllTrajectoryBuilderOptions::default_instance();
}
inline ::cartographer::mapping::proto::AllTrajectoryBuilderOptions* SerializedData::mutable_all_trajectory_builder_options() {
  if (!has_all_trajectory_builder_options()) {
    clear_data();
    set_has_all_trajectory_builder_options();
    data_.all_trajectory_builder_options_ = new ::cartographer::mapping::proto::AllTrajectoryBuilderOptions;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.SerializedData.all_trajectory_builder_options)
  return data_.all_trajectory_builder_options_;
}
inline ::cartographer::mapping::proto::AllTrajectoryBuilderOptions* SerializedData::release_all_trajectory_builder_options() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.SerializedData.all_trajectory_builder_options)
  if (has_all_trajectory_builder_options()) {
    clear_has_data();
    ::cartographer::mapping::proto::AllTrajectoryBuilderOptions* temp = data_.all_trajectory_builder_options_;
    data_.all_trajectory_builder_options_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void SerializedData::set_allocated_all_trajectory_builder_options(::cartographer::mapping::proto::AllTrajectoryBuilderOptions* all_trajectory_builder_options) {
  clear_data();
  if (all_trajectory_builder_options) {
    set_has_all_trajectory_builder_options();
    data_.all_trajectory_builder_options_ = all_trajectory_builder_options;
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.SerializedData.all_trajectory_builder_options)
}

// optional .cartographer.mapping.proto.Submap submap = 3;
inline bool SerializedData::has_submap() const {
  return data_case() == kSubmap;
}
inline void SerializedData::set_has_submap() {
  _oneof_case_[0] = kSubmap;
}
inline void SerializedData::clear_submap() {
  if (has_submap()) {
    delete data_.submap_;
    clear_has_data();
  }
}
inline  const ::cartographer::mapping::proto::Submap& SerializedData::submap() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.SerializedData.submap)
  return has_submap()
      ? *data_.submap_
      : ::cartographer::mapping::proto::Submap::default_instance();
}
inline ::cartographer::mapping::proto::Submap* SerializedData::mutable_submap() {
  if (!has_submap()) {
    clear_data();
    set_has_submap();
    data_.submap_ = new ::cartographer::mapping::proto::Submap;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.SerializedData.submap)
  return data_.submap_;
}
inline ::cartographer::mapping::proto::Submap* SerializedData::release_submap() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.SerializedData.submap)
  if (has_submap()) {
    clear_has_data();
    ::cartographer::mapping::proto::Submap* temp = data_.submap_;
    data_.submap_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void SerializedData::set_allocated_submap(::cartographer::mapping::proto::Submap* submap) {
  clear_data();
  if (submap) {
    set_has_submap();
    data_.submap_ = submap;
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.SerializedData.submap)
}

// optional .cartographer.mapping.proto.Node node = 4;
inline bool SerializedData::has_node() const {
  return data_case() == kNode;
}
inline void SerializedData::set_has_node() {
  _oneof_case_[0] = kNode;
}
inline void SerializedData::clear_node() {
  if (has_node()) {
    delete data_.node_;
    clear_has_data();
  }
}
inline  const ::cartographer::mapping::proto::Node& SerializedData::node() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.SerializedData.node)
  return has_node()
      ? *data_.node_
      : ::cartographer::mapping::proto::Node::default_instance();
}
inline ::cartographer::mapping::proto::Node* SerializedData::mutable_node() {
  if (!has_node()) {
    clear_data();
    set_has_node();
    data_.node_ = new ::cartographer::mapping::proto::Node;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.SerializedData.node)
  return data_.node_;
}
inline ::cartographer::mapping::proto::Node* SerializedData::release_node() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.SerializedData.node)
  if (has_node()) {
    clear_has_data();
    ::cartographer::mapping::proto::Node* temp = data_.node_;
    data_.node_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void SerializedData::set_allocated_node(::cartographer::mapping::proto::Node* node) {
  clear_data();
  if (node) {
    set_has_node();
    data_.node_ = node;
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.SerializedData.node)
}

// optional .cartographer.mapping.proto.TrajectoryData trajectory_data = 5;
inline bool SerializedData::has_trajectory_data() const {
  return data_case() == kTrajectoryData;
}
inline void SerializedData::set_has_trajectory_data() {
  _oneof_case_[0] = kTrajectoryData;
}
inline void SerializedData::clear_trajectory_data() {
  if (has_trajectory_data()) {
    delete data_.trajectory_data_;
    clear_has_data();
  }
}
inline  const ::cartographer::mapping::proto::TrajectoryData& SerializedData::trajectory_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.SerializedData.trajectory_data)
  return has_trajectory_data()
      ? *data_.trajectory_data_
      : ::cartographer::mapping::proto::TrajectoryData::default_instance();
}
inline ::cartographer::mapping::proto::TrajectoryData* SerializedData::mutable_trajectory_data() {
  if (!has_trajectory_data()) {
    clear_data();
    set_has_trajectory_data();
    data_.trajectory_data_ = new ::cartographer::mapping::proto::TrajectoryData;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.SerializedData.trajectory_data)
  return data_.trajectory_data_;
}
inline ::cartographer::mapping::proto::TrajectoryData* SerializedData::release_trajectory_data() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.SerializedData.trajectory_data)
  if (has_trajectory_data()) {
    clear_has_data();
    ::cartographer::mapping::proto::TrajectoryData* temp = data_.trajectory_data_;
    data_.trajectory_data_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void SerializedData::set_allocated_trajectory_data(::cartographer::mapping::proto::TrajectoryData* trajectory_data) {
  clear_data();
  if (trajectory_data) {
    set_has_trajectory_data();
    data_.trajectory_data_ = trajectory_data;
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.SerializedData.trajectory_data)
}

// optional .cartographer.mapping.proto.ImuData imu_data = 6;
inline bool SerializedData::has_imu_data() const {
  return data_case() == kImuData;
}
inline void SerializedData::set_has_imu_data() {
  _oneof_case_[0] = kImuData;
}
inline void SerializedData::clear_imu_data() {
  if (has_imu_data()) {
    delete data_.imu_data_;
    clear_has_data();
  }
}
inline  const ::cartographer::mapping::proto::ImuData& SerializedData::imu_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.SerializedData.imu_data)
  return has_imu_data()
      ? *data_.imu_data_
      : ::cartographer::mapping::proto::ImuData::default_instance();
}
inline ::cartographer::mapping::proto::ImuData* SerializedData::mutable_imu_data() {
  if (!has_imu_data()) {
    clear_data();
    set_has_imu_data();
    data_.imu_data_ = new ::cartographer::mapping::proto::ImuData;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.SerializedData.imu_data)
  return data_.imu_data_;
}
inline ::cartographer::mapping::proto::ImuData* SerializedData::release_imu_data() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.SerializedData.imu_data)
  if (has_imu_data()) {
    clear_has_data();
    ::cartographer::mapping::proto::ImuData* temp = data_.imu_data_;
    data_.imu_data_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void SerializedData::set_allocated_imu_data(::cartographer::mapping::proto::ImuData* imu_data) {
  clear_data();
  if (imu_data) {
    set_has_imu_data();
    data_.imu_data_ = imu_data;
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.SerializedData.imu_data)
}

// optional .cartographer.mapping.proto.OdometryData odometry_data = 7;
inline bool SerializedData::has_odometry_data() const {
  return data_case() == kOdometryData;
}
inline void SerializedData::set_has_odometry_data() {
  _oneof_case_[0] = kOdometryData;
}
inline void SerializedData::clear_odometry_data() {
  if (has_odometry_data()) {
    delete data_.odometry_data_;
    clear_has_data();
  }
}
inline  const ::cartographer::mapping::proto::OdometryData& SerializedData::odometry_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.SerializedData.odometry_data)
  return has_odometry_data()
      ? *data_.odometry_data_
      : ::cartographer::mapping::proto::OdometryData::default_instance();
}
inline ::cartographer::mapping::proto::OdometryData* SerializedData::mutable_odometry_data() {
  if (!has_odometry_data()) {
    clear_data();
    set_has_odometry_data();
    data_.odometry_data_ = new ::cartographer::mapping::proto::OdometryData;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.SerializedData.odometry_data)
  return data_.odometry_data_;
}
inline ::cartographer::mapping::proto::OdometryData* SerializedData::release_odometry_data() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.SerializedData.odometry_data)
  if (has_odometry_data()) {
    clear_has_data();
    ::cartographer::mapping::proto::OdometryData* temp = data_.odometry_data_;
    data_.odometry_data_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void SerializedData::set_allocated_odometry_data(::cartographer::mapping::proto::OdometryData* odometry_data) {
  clear_data();
  if (odometry_data) {
    set_has_odometry_data();
    data_.odometry_data_ = odometry_data;
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.SerializedData.odometry_data)
}

// optional .cartographer.mapping.proto.FixedFramePoseData fixed_frame_pose_data = 8;
inline bool SerializedData::has_fixed_frame_pose_data() const {
  return data_case() == kFixedFramePoseData;
}
inline void SerializedData::set_has_fixed_frame_pose_data() {
  _oneof_case_[0] = kFixedFramePoseData;
}
inline void SerializedData::clear_fixed_frame_pose_data() {
  if (has_fixed_frame_pose_data()) {
    delete data_.fixed_frame_pose_data_;
    clear_has_data();
  }
}
inline  const ::cartographer::mapping::proto::FixedFramePoseData& SerializedData::fixed_frame_pose_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.SerializedData.fixed_frame_pose_data)
  return has_fixed_frame_pose_data()
      ? *data_.fixed_frame_pose_data_
      : ::cartographer::mapping::proto::FixedFramePoseData::default_instance();
}
inline ::cartographer::mapping::proto::FixedFramePoseData* SerializedData::mutable_fixed_frame_pose_data() {
  if (!has_fixed_frame_pose_data()) {
    clear_data();
    set_has_fixed_frame_pose_data();
    data_.fixed_frame_pose_data_ = new ::cartographer::mapping::proto::FixedFramePoseData;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.SerializedData.fixed_frame_pose_data)
  return data_.fixed_frame_pose_data_;
}
inline ::cartographer::mapping::proto::FixedFramePoseData* SerializedData::release_fixed_frame_pose_data() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.SerializedData.fixed_frame_pose_data)
  if (has_fixed_frame_pose_data()) {
    clear_has_data();
    ::cartographer::mapping::proto::FixedFramePoseData* temp = data_.fixed_frame_pose_data_;
    data_.fixed_frame_pose_data_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void SerializedData::set_allocated_fixed_frame_pose_data(::cartographer::mapping::proto::FixedFramePoseData* fixed_frame_pose_data) {
  clear_data();
  if (fixed_frame_pose_data) {
    set_has_fixed_frame_pose_data();
    data_.fixed_frame_pose_data_ = fixed_frame_pose_data;
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.SerializedData.fixed_frame_pose_data)
}

// optional .cartographer.mapping.proto.LandmarkData landmark_data = 9;
inline bool SerializedData::has_landmark_data() const {
  return data_case() == kLandmarkData;
}
inline void SerializedData::set_has_landmark_data() {
  _oneof_case_[0] = kLandmarkData;
}
inline void SerializedData::clear_landmark_data() {
  if (has_landmark_data()) {
    delete data_.landmark_data_;
    clear_has_data();
  }
}
inline  const ::cartographer::mapping::proto::LandmarkData& SerializedData::landmark_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.SerializedData.landmark_data)
  return has_landmark_data()
      ? *data_.landmark_data_
      : ::cartographer::mapping::proto::LandmarkData::default_instance();
}
inline ::cartographer::mapping::proto::LandmarkData* SerializedData::mutable_landmark_data() {
  if (!has_landmark_data()) {
    clear_data();
    set_has_landmark_data();
    data_.landmark_data_ = new ::cartographer::mapping::proto::LandmarkData;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.SerializedData.landmark_data)
  return data_.landmark_data_;
}
inline ::cartographer::mapping::proto::LandmarkData* SerializedData::release_landmark_data() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.SerializedData.landmark_data)
  if (has_landmark_data()) {
    clear_has_data();
    ::cartographer::mapping::proto::LandmarkData* temp = data_.landmark_data_;
    data_.landmark_data_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void SerializedData::set_allocated_landmark_data(::cartographer::mapping::proto::LandmarkData* landmark_data) {
  clear_data();
  if (landmark_data) {
    set_has_landmark_data();
    data_.landmark_data_ = landmark_data;
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.SerializedData.landmark_data)
}

inline bool SerializedData::has_data() const {
  return data_case() != DATA_NOT_SET;
}
inline void SerializedData::clear_has_data() {
  _oneof_case_[0] = DATA_NOT_SET;
}
inline SerializedData::DataCase SerializedData::data_case() const {
  return SerializedData::DataCase(_oneof_case_[0]);
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_2fproto_2fserialization_2eproto__INCLUDED
