// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_3d.proto

#ifndef PROTOBUF_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f3d_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f3d_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace mapping {
namespace scan_matching {
namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f3d_2eproto();
void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f3d_2eproto();
void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f3d_2eproto();

class FastCorrelativeScanMatcherOptions3D;

// ===================================================================

class FastCorrelativeScanMatcherOptions3D : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D) */ {
 public:
  FastCorrelativeScanMatcherOptions3D();
  virtual ~FastCorrelativeScanMatcherOptions3D();

  FastCorrelativeScanMatcherOptions3D(const FastCorrelativeScanMatcherOptions3D& from);

  inline FastCorrelativeScanMatcherOptions3D& operator=(const FastCorrelativeScanMatcherOptions3D& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FastCorrelativeScanMatcherOptions3D& default_instance();

  void Swap(FastCorrelativeScanMatcherOptions3D* other);

  // implements Message ----------------------------------------------

  inline FastCorrelativeScanMatcherOptions3D* New() const { return New(NULL); }

  FastCorrelativeScanMatcherOptions3D* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FastCorrelativeScanMatcherOptions3D& from);
  void MergeFrom(const FastCorrelativeScanMatcherOptions3D& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FastCorrelativeScanMatcherOptions3D* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 branch_and_bound_depth = 2;
  void clear_branch_and_bound_depth();
  static const int kBranchAndBoundDepthFieldNumber = 2;
  ::google::protobuf::int32 branch_and_bound_depth() const;
  void set_branch_and_bound_depth(::google::protobuf::int32 value);

  // optional int32 full_resolution_depth = 8;
  void clear_full_resolution_depth();
  static const int kFullResolutionDepthFieldNumber = 8;
  ::google::protobuf::int32 full_resolution_depth() const;
  void set_full_resolution_depth(::google::protobuf::int32 value);

  // optional double min_rotational_score = 4;
  void clear_min_rotational_score();
  static const int kMinRotationalScoreFieldNumber = 4;
  double min_rotational_score() const;
  void set_min_rotational_score(double value);

  // optional double min_low_resolution_score = 9;
  void clear_min_low_resolution_score();
  static const int kMinLowResolutionScoreFieldNumber = 9;
  double min_low_resolution_score() const;
  void set_min_low_resolution_score(double value);

  // optional double linear_xy_search_window = 5;
  void clear_linear_xy_search_window();
  static const int kLinearXySearchWindowFieldNumber = 5;
  double linear_xy_search_window() const;
  void set_linear_xy_search_window(double value);

  // optional double linear_z_search_window = 6;
  void clear_linear_z_search_window();
  static const int kLinearZSearchWindowFieldNumber = 6;
  double linear_z_search_window() const;
  void set_linear_z_search_window(double value);

  // optional double angular_search_window = 7;
  void clear_angular_search_window();
  static const int kAngularSearchWindowFieldNumber = 7;
  double angular_search_window() const;
  void set_angular_search_window(double value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 branch_and_bound_depth_;
  ::google::protobuf::int32 full_resolution_depth_;
  double min_rotational_score_;
  double min_low_resolution_score_;
  double linear_xy_search_window_;
  double linear_z_search_window_;
  double angular_search_window_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f3d_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f3d_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f3d_2eproto();

  void InitAsDefaultInstance();
  static FastCorrelativeScanMatcherOptions3D* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// FastCorrelativeScanMatcherOptions3D

// optional int32 branch_and_bound_depth = 2;
inline void FastCorrelativeScanMatcherOptions3D::clear_branch_and_bound_depth() {
  branch_and_bound_depth_ = 0;
}
inline ::google::protobuf::int32 FastCorrelativeScanMatcherOptions3D::branch_and_bound_depth() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.branch_and_bound_depth)
  return branch_and_bound_depth_;
}
inline void FastCorrelativeScanMatcherOptions3D::set_branch_and_bound_depth(::google::protobuf::int32 value) {
  
  branch_and_bound_depth_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.branch_and_bound_depth)
}

// optional int32 full_resolution_depth = 8;
inline void FastCorrelativeScanMatcherOptions3D::clear_full_resolution_depth() {
  full_resolution_depth_ = 0;
}
inline ::google::protobuf::int32 FastCorrelativeScanMatcherOptions3D::full_resolution_depth() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.full_resolution_depth)
  return full_resolution_depth_;
}
inline void FastCorrelativeScanMatcherOptions3D::set_full_resolution_depth(::google::protobuf::int32 value) {
  
  full_resolution_depth_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.full_resolution_depth)
}

// optional double min_rotational_score = 4;
inline void FastCorrelativeScanMatcherOptions3D::clear_min_rotational_score() {
  min_rotational_score_ = 0;
}
inline double FastCorrelativeScanMatcherOptions3D::min_rotational_score() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.min_rotational_score)
  return min_rotational_score_;
}
inline void FastCorrelativeScanMatcherOptions3D::set_min_rotational_score(double value) {
  
  min_rotational_score_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.min_rotational_score)
}

// optional double min_low_resolution_score = 9;
inline void FastCorrelativeScanMatcherOptions3D::clear_min_low_resolution_score() {
  min_low_resolution_score_ = 0;
}
inline double FastCorrelativeScanMatcherOptions3D::min_low_resolution_score() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.min_low_resolution_score)
  return min_low_resolution_score_;
}
inline void FastCorrelativeScanMatcherOptions3D::set_min_low_resolution_score(double value) {
  
  min_low_resolution_score_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.min_low_resolution_score)
}

// optional double linear_xy_search_window = 5;
inline void FastCorrelativeScanMatcherOptions3D::clear_linear_xy_search_window() {
  linear_xy_search_window_ = 0;
}
inline double FastCorrelativeScanMatcherOptions3D::linear_xy_search_window() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.linear_xy_search_window)
  return linear_xy_search_window_;
}
inline void FastCorrelativeScanMatcherOptions3D::set_linear_xy_search_window(double value) {
  
  linear_xy_search_window_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.linear_xy_search_window)
}

// optional double linear_z_search_window = 6;
inline void FastCorrelativeScanMatcherOptions3D::clear_linear_z_search_window() {
  linear_z_search_window_ = 0;
}
inline double FastCorrelativeScanMatcherOptions3D::linear_z_search_window() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.linear_z_search_window)
  return linear_z_search_window_;
}
inline void FastCorrelativeScanMatcherOptions3D::set_linear_z_search_window(double value) {
  
  linear_z_search_window_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.linear_z_search_window)
}

// optional double angular_search_window = 7;
inline void FastCorrelativeScanMatcherOptions3D::clear_angular_search_window() {
  angular_search_window_ = 0;
}
inline double FastCorrelativeScanMatcherOptions3D::angular_search_window() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.angular_search_window)
  return angular_search_window_;
}
inline void FastCorrelativeScanMatcherOptions3D::set_angular_search_window(double value) {
  
  angular_search_window_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.angular_search_window)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace scan_matching
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_2fproto_2fscan_5fmatching_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_5f3d_2eproto__INCLUDED
